services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "${WEB_SERVER_PORT}:80"
      - "8081:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`tip.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173" # Vite default port
    depends_on:
      - backend-node
      - backend-python

  backend-node:
    build:
      context: ./backend-node
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend-node:/app
      - /app/node_modules
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-node.rule=Host(`api.tip.localhost`)"
      - "traefik.http.routers.backend-node.entrypoints=web"
      - "traefik.http.services.backend-node.loadbalancer.server.port=3000"
    depends_on:
      - db
      - redis

  backend-python:
    build:
      context: ./backend-python
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend-python:/app
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-python.rule=Host(`py.tip.localhost`)"
      - "traefik.http.routers.backend-python.entrypoints=web"
      - "traefik.http.services.backend-python.loadbalancer.server.port=8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env
    command: server /data --console-address ":9001"

  n8n:
    image: n8nio/n8n
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.tip.localhost`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    command: start-dev
    env_file:
      - .env
    ports:
      - "${PYTHON_APP_PORT}:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.tip.localhost`)"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

volumes:
  postgres_data:
  minio_data:
  n8n_data: